package main;

import static java.lang.Integer.max;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BQC
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
        this.setSize(325, 390);
        tfDisplay.setOpaque(false);
        tfDisplay.setEditable(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBackspace = new javax.swing.JLabel();
        lbMultiple = new javax.swing.JLabel();
        lbDivide = new javax.swing.JLabel();
        lbClear = new javax.swing.JLabel();
        lbMinus = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lbPlus = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lbParentheless = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lbEqual = new javax.swing.JLabel();
        lbNeg_Pos = new javax.swing.JLabel();
        lbDot = new javax.swing.JLabel();
        lb0 = new javax.swing.JLabel();
        tfDisplay = new javax.swing.JTextField();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(320, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        lbBackspace.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbBackspace.setForeground(new java.awt.Color(255, 204, 0));
        lbBackspace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBackspace.setText("<");
        lbBackspace.setMaximumSize(new java.awt.Dimension(14, 28));
        lbBackspace.setMinimumSize(new java.awt.Dimension(14, 28));
        lbBackspace.setPreferredSize(new java.awt.Dimension(14, 28));
        lbBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackspaceMouseClicked(evt);
            }
        });
        getContentPane().add(lbBackspace);
        lbBackspace.setBounds(242, 118, 69, 40);

        lbMultiple.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbMultiple.setForeground(new java.awt.Color(255, 204, 0));
        lbMultiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMultiple.setText("x");
        lbMultiple.setMaximumSize(new java.awt.Dimension(14, 28));
        lbMultiple.setMinimumSize(new java.awt.Dimension(14, 28));
        lbMultiple.setPreferredSize(new java.awt.Dimension(14, 28));
        lbMultiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMultipleMouseClicked(evt);
            }
        });
        getContentPane().add(lbMultiple);
        lbMultiple.setBounds(165, 118, 69, 40);

        lbDivide.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDivide.setForeground(new java.awt.Color(255, 204, 0));
        lbDivide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDivide.setText("÷");
        lbDivide.setMaximumSize(new java.awt.Dimension(14, 28));
        lbDivide.setMinimumSize(new java.awt.Dimension(14, 28));
        lbDivide.setPreferredSize(new java.awt.Dimension(14, 28));
        lbDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDivideMouseClicked(evt);
            }
        });
        getContentPane().add(lbDivide);
        lbDivide.setBounds(88, 118, 69, 40);

        lbClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbClear.setForeground(new java.awt.Color(255, 204, 0));
        lbClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClear.setText("C");
        lbClear.setMaximumSize(new java.awt.Dimension(14, 28));
        lbClear.setMinimumSize(new java.awt.Dimension(14, 28));
        lbClear.setPreferredSize(new java.awt.Dimension(14, 28));
        lbClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbClearMouseClicked(evt);
            }
        });
        getContentPane().add(lbClear);
        lbClear.setBounds(11, 118, 69, 40);

        lbMinus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbMinus.setForeground(new java.awt.Color(255, 204, 0));
        lbMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMinus.setText("̶");
        lbMinus.setMaximumSize(new java.awt.Dimension(14, 28));
        lbMinus.setMinimumSize(new java.awt.Dimension(14, 28));
        lbMinus.setPreferredSize(new java.awt.Dimension(14, 28));
        lbMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinusMouseClicked(evt);
            }
        });
        getContentPane().add(lbMinus);
        lbMinus.setBounds(242, 167, 69, 40);

        lb9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb9.setForeground(new java.awt.Color(255, 204, 0));
        lb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb9.setText("9");
        lb9.setMaximumSize(new java.awt.Dimension(14, 28));
        lb9.setMinimumSize(new java.awt.Dimension(14, 28));
        lb9.setPreferredSize(new java.awt.Dimension(14, 28));
        lb9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb9MouseClicked(evt);
            }
        });
        getContentPane().add(lb9);
        lb9.setBounds(165, 167, 69, 40);

        lb8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb8.setForeground(new java.awt.Color(255, 204, 0));
        lb8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb8.setText("8");
        lb8.setMaximumSize(new java.awt.Dimension(14, 28));
        lb8.setMinimumSize(new java.awt.Dimension(14, 28));
        lb8.setPreferredSize(new java.awt.Dimension(14, 28));
        lb8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb8MouseClicked(evt);
            }
        });
        getContentPane().add(lb8);
        lb8.setBounds(88, 167, 69, 40);

        lb7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb7.setForeground(new java.awt.Color(255, 204, 0));
        lb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb7.setText("7");
        lb7.setMaximumSize(new java.awt.Dimension(14, 28));
        lb7.setMinimumSize(new java.awt.Dimension(14, 28));
        lb7.setPreferredSize(new java.awt.Dimension(14, 28));
        lb7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb7MouseClicked(evt);
            }
        });
        getContentPane().add(lb7);
        lb7.setBounds(11, 167, 69, 40);

        lbPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPlus.setForeground(new java.awt.Color(255, 204, 0));
        lbPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlus.setText("+");
        lbPlus.setMaximumSize(new java.awt.Dimension(14, 28));
        lbPlus.setMinimumSize(new java.awt.Dimension(14, 28));
        lbPlus.setPreferredSize(new java.awt.Dimension(14, 28));
        lbPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlusMouseClicked(evt);
            }
        });
        getContentPane().add(lbPlus);
        lbPlus.setBounds(242, 215, 69, 40);

        lb6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 204, 0));
        lb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb6.setText("6");
        lb6.setMaximumSize(new java.awt.Dimension(14, 28));
        lb6.setMinimumSize(new java.awt.Dimension(14, 28));
        lb6.setPreferredSize(new java.awt.Dimension(14, 28));
        lb6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb6MouseClicked(evt);
            }
        });
        getContentPane().add(lb6);
        lb6.setBounds(165, 215, 69, 40);

        lb5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 204, 0));
        lb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb5.setText("5");
        lb5.setMaximumSize(new java.awt.Dimension(14, 28));
        lb5.setMinimumSize(new java.awt.Dimension(14, 28));
        lb5.setPreferredSize(new java.awt.Dimension(14, 28));
        lb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb5MouseClicked(evt);
            }
        });
        getContentPane().add(lb5);
        lb5.setBounds(88, 215, 69, 40);

        lb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 204, 0));
        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb4.setText("4");
        lb4.setMaximumSize(new java.awt.Dimension(14, 28));
        lb4.setMinimumSize(new java.awt.Dimension(14, 28));
        lb4.setPreferredSize(new java.awt.Dimension(14, 28));
        lb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb4MouseClicked(evt);
            }
        });
        getContentPane().add(lb4);
        lb4.setBounds(11, 215, 69, 40);

        lbParentheless.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbParentheless.setForeground(new java.awt.Color(255, 204, 0));
        lbParentheless.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbParentheless.setText("( )");
        lbParentheless.setMaximumSize(new java.awt.Dimension(14, 28));
        lbParentheless.setMinimumSize(new java.awt.Dimension(14, 28));
        lbParentheless.setPreferredSize(new java.awt.Dimension(14, 28));
        lbParentheless.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbParenthelessMouseClicked(evt);
            }
        });
        getContentPane().add(lbParentheless);
        lbParentheless.setBounds(242, 264, 69, 40);

        lb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 204, 0));
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("3");
        lb3.setMaximumSize(new java.awt.Dimension(14, 28));
        lb3.setMinimumSize(new java.awt.Dimension(14, 28));
        lb3.setPreferredSize(new java.awt.Dimension(14, 28));
        lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3MouseClicked(evt);
            }
        });
        getContentPane().add(lb3);
        lb3.setBounds(165, 264, 69, 40);

        lb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 204, 0));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("2");
        lb2.setMaximumSize(new java.awt.Dimension(14, 28));
        lb2.setMinimumSize(new java.awt.Dimension(14, 28));
        lb2.setPreferredSize(new java.awt.Dimension(14, 28));
        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2MouseClicked(evt);
            }
        });
        getContentPane().add(lb2);
        lb2.setBounds(88, 264, 69, 40);

        lb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 204, 0));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("1");
        lb1.setMaximumSize(new java.awt.Dimension(14, 28));
        lb1.setMinimumSize(new java.awt.Dimension(14, 28));
        lb1.setPreferredSize(new java.awt.Dimension(14, 28));
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb1MouseClicked(evt);
            }
        });
        getContentPane().add(lb1);
        lb1.setBounds(11, 264, 69, 40);

        lbEqual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEqual.setForeground(new java.awt.Color(255, 204, 0));
        lbEqual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEqual.setText("=");
        lbEqual.setMaximumSize(new java.awt.Dimension(14, 28));
        lbEqual.setMinimumSize(new java.awt.Dimension(14, 28));
        lbEqual.setPreferredSize(new java.awt.Dimension(14, 28));
        lbEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEqualMouseClicked(evt);
            }
        });
        getContentPane().add(lbEqual);
        lbEqual.setBounds(242, 314, 69, 40);

        lbNeg_Pos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNeg_Pos.setForeground(new java.awt.Color(255, 204, 0));
        lbNeg_Pos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNeg_Pos.setText("+/-");
        lbNeg_Pos.setMaximumSize(new java.awt.Dimension(14, 28));
        lbNeg_Pos.setMinimumSize(new java.awt.Dimension(14, 28));
        lbNeg_Pos.setPreferredSize(new java.awt.Dimension(14, 28));
        lbNeg_Pos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNeg_PosMouseClicked(evt);
            }
        });
        getContentPane().add(lbNeg_Pos);
        lbNeg_Pos.setBounds(165, 314, 69, 40);

        lbDot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDot.setForeground(new java.awt.Color(255, 204, 0));
        lbDot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDot.setText(".");
        lbDot.setMaximumSize(new java.awt.Dimension(14, 28));
        lbDot.setMinimumSize(new java.awt.Dimension(14, 28));
        lbDot.setPreferredSize(new java.awt.Dimension(14, 28));
        lbDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDotMouseClicked(evt);
            }
        });
        getContentPane().add(lbDot);
        lbDot.setBounds(88, 314, 69, 40);

        lb0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb0.setForeground(new java.awt.Color(255, 204, 0));
        lb0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb0.setText("0");
        lb0.setMaximumSize(new java.awt.Dimension(14, 28));
        lb0.setMinimumSize(new java.awt.Dimension(14, 28));
        lb0.setPreferredSize(new java.awt.Dimension(14, 28));
        lb0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb0MouseClicked(evt);
            }
        });
        getContentPane().add(lb0);
        lb0.setBounds(11, 314, 69, 40);

        tfDisplay.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfDisplay.setForeground(new java.awt.Color(255, 102, 0));
        tfDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDisplay.setBorder(null);
        tfDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDisplayMouseClicked(evt);
            }
        });
        getContentPane().add(tfDisplay);
        tfDisplay.setBounds(10, 35, 300, 50);

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/calculator.png"))); // NOI18N
        getContentPane().add(lbBackground);
        lbBackground.setBounds(0, 0, 320, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lb0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb0MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "0");
    }//GEN-LAST:event_lb0MouseClicked

    private void lbDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDotMouseClicked
        isHoldingAnswer = false;
        int posOperator = nearestOperator();
        int posDot = tfDisplay.getText().lastIndexOf(".");
        if (posDot > posOperator) {
            return ;
        }
        tfDisplay.setText(tfDisplay.getText()+".");
    }//GEN-LAST:event_lbDotMouseClicked
    
    private void lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "1");
    }//GEN-LAST:event_lb1MouseClicked

    private void lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "2");
    }//GEN-LAST:event_lb2MouseClicked

    private void lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "3");
    }//GEN-LAST:event_lb3MouseClicked

    private void lb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb4MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "4");
    }//GEN-LAST:event_lb4MouseClicked

    private void lb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "5");
    }//GEN-LAST:event_lb5MouseClicked

    private void lb6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb6MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "6");
    }//GEN-LAST:event_lb6MouseClicked

    private void lb7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb7MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "7");
    }//GEN-LAST:event_lb7MouseClicked

    private void lb8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb8MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "8");
    }//GEN-LAST:event_lb8MouseClicked

    private void lb9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb9MouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        tfDisplay.setText(tfDisplay.getText() + "9");
    }//GEN-LAST:event_lb9MouseClicked

    private void lbClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbClearMouseClicked
        tfDisplay.setText("");
        isHoldingAnswer = false;
    }//GEN-LAST:event_lbClearMouseClicked

    private void lbDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDivideMouseClicked
        StringBuilder text = new StringBuilder(tfDisplay.getText());
        int length = text.length();
        
        if (length > 0) {
            if (isOperator(text.charAt(length-1))) {
                text.replace(length-1, length, "/");
            }
            else text.append("/");
            
            tfDisplay.setText(text.toString());
            isHoldingAnswer = false;
        }        
    }//GEN-LAST:event_lbDivideMouseClicked

    private void lbMultipleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMultipleMouseClicked
        StringBuilder text = new StringBuilder(tfDisplay.getText());
        int length = text.length();
        
        if (length > 0) {
            if (isOperator(text.charAt(length-1))) {
                text.replace(length-1, length, "*");
            }
            else text.append("*");
            
            tfDisplay.setText(text.toString());
            isHoldingAnswer = false;
        }
    }//GEN-LAST:event_lbMultipleMouseClicked

    private void lbMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinusMouseClicked
        StringBuilder text = new StringBuilder(tfDisplay.getText());
        int length = text.length();
        
        if (length > 0) {
            if (isOperator(text.charAt(length-1))) {
                text.replace(length-1, length, "-");
            }
            else text.append("-");
            
            tfDisplay.setText(text.toString());
            isHoldingAnswer = false;
        }
    }//GEN-LAST:event_lbMinusMouseClicked

    private void lbPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlusMouseClicked
        StringBuilder text = new StringBuilder(tfDisplay.getText());
        int length = text.length();
        
        if (length > 0) {
            if (isOperator(text.charAt(length-1))) {
                text.replace(length-1, length, "+");
            }
            else text.append("+");
            
            tfDisplay.setText(text.toString());
            isHoldingAnswer = false;
        }
    }//GEN-LAST:event_lbPlusMouseClicked

    private void lbBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackspaceMouseClicked
        if (isHoldingAnswer) {
            tfDisplay.setText("");
            isHoldingAnswer = false;
        }
        
        String text = tfDisplay.getText();
        if (!text.isEmpty()) {
            tfDisplay.setText(text.substring(0, text.length()-1));
        }
    }//GEN-LAST:event_lbBackspaceMouseClicked

    private void lbEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEqualMouseClicked
        
        autoAddParentheses();
        
        ScriptEngineManager SEM = new ScriptEngineManager();
        ScriptEngine SE = SEM.getEngineByName("JavaScript");
        
        try {
            isHoldingAnswer = true;
            tfDisplay.setText(SE.eval(tfDisplay.getText()).toString());
            
            
        } catch (ScriptException ex) {
            JOptionPane.showMessageDialog(null, "\rLỗi rồi thím ơi! \n\rXem lại giùm đi!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbEqualMouseClicked

    private void lbNeg_PosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNeg_PosMouseClicked
        String text = tfDisplay.getText();
        if (text.isEmpty()) {
            tfDisplay.setText(tfDisplay.getText() + "(-");
            return ;
        }
        boolean condition = Character.isDigit(text.charAt(text.length()-1));
        isHoldingAnswer = false;
        
        if (text.isEmpty() || !condition) {
            tfDisplay.setText(tfDisplay.getText() + "(-");
        } else if (condition) {
            tfDisplay.setText(tfDisplay.getText() + "*(-");
        }
    }//GEN-LAST:event_lbNeg_PosMouseClicked

    private void lbParenthelessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbParenthelessMouseClicked
        String text = tfDisplay.getText();
        if (text.isEmpty()) {
            tfDisplay.setText(tfDisplay.getText() + "(");
            return ;
        }
        int len = text.length();
        char lastChar = text.charAt(len-1);
        isHoldingAnswer = false;
        
        int numOfParentheses = countParentheses();
        
        if (lastChar == '(' ||
            (len != 1 && text.lastIndexOf("(-") == len-2)
            || isOperator(text.charAt(len-1))) {
            tfDisplay.setText(tfDisplay.getText() + "(");
            numOfParentheses++;
        }
        else if (Character.isDigit(lastChar)
                 || lastChar == ')') {
            if (numOfParentheses > 0) {
                tfDisplay.setText(tfDisplay.getText() + ")");
                numOfParentheses--;
            } else {
                tfDisplay.setText(tfDisplay.getText() + "*(");
                numOfParentheses++;
            }
        }
        
    }//GEN-LAST:event_lbParenthelessMouseClicked

    private void tfDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDisplayMouseClicked
        ImageIcon ico = new ImageIcon("./src/files/icon.png");
        //Icon icon = new ;
        if (evt.getClickCount() == 2) {
            JOptionPane.showMessageDialog(null, "A mini emulated calculator\nby BQC!", "About", JOptionPane.PLAIN_MESSAGE, ico);
        }
    }//GEN-LAST:event_tfDisplayMouseClicked
    
    private int countParentheses() {
        String text = tfDisplay.getText();
        // count number of Parentheseses
        int numOfParentheses = 0;
        int found = text.indexOf("(", 0);
        
        while (found != -1) {
            numOfParentheses++;
            found = text.indexOf("(", found+1);
        }
        //
        found = text.indexOf(")", 0);
        while (found != -1) {
            numOfParentheses--;
            found = text.indexOf(")", found+1);
        }
        // end count
        return numOfParentheses;
    }
    
    private void autoAddParentheses() {
        StringBuilder text = new StringBuilder(tfDisplay.getText());
        int numOfParentheses = countParentheses();
        
        while (numOfParentheses-- > 0) {
            text.append(")");
        }
        
        int found;
        
        if ((found = text.indexOf("+()")) != -1 || (found = text.indexOf("-()")) != -1) {
            text.insert(found+2, "0");
        } else if ((found = text.indexOf("*()")) != -1 || (found = text.indexOf("/()")) != -1) {
            text.insert(found+2, "1");
        }
        
        tfDisplay.setText(text.toString());
    }
    
    private boolean isOperator(char ch) {
        if (ch == PLUS || ch == MINUS || ch == MULTIPLE || ch == DIVIDE) {
            return true;
            
        } else return false;
    }
    
    private int nearestOperator() {
        String text = tfDisplay.getText();
        int plu = text.lastIndexOf(PLUS);
        int mi = text.lastIndexOf(MINUS);
        int mul = text.lastIndexOf(MULTIPLE);
        int div = text.lastIndexOf(DIVIDE);
        return max(plu, max(mi, max(mul, div)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb0;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbBackspace;
    private javax.swing.JLabel lbClear;
    private javax.swing.JLabel lbDivide;
    private javax.swing.JLabel lbDot;
    private javax.swing.JLabel lbEqual;
    private javax.swing.JLabel lbMinus;
    private javax.swing.JLabel lbMultiple;
    private javax.swing.JLabel lbNeg_Pos;
    private javax.swing.JLabel lbParentheless;
    private javax.swing.JLabel lbPlus;
    private javax.swing.JTextField tfDisplay;
    // End of variables declaration//GEN-END:variables
    final static private char PLUS = '+';
    final static private char MINUS = '-';
    final static private char MULTIPLE = '*';
    final static private char DIVIDE = '/';
    private boolean isHoldingAnswer = false;
}
